### ISSUE TITLE
Code documentation

### ISSUE THREAD

**Issue by hamidafghan** [wahrez/androidApp#1]
Try to give descriptive and helpful code documentation. Let's change the 'redirect' to 'navigate'. It makes more seance. @wahrez

**Comment by wahrez** [comment]
Thanks, sir, from your collaboration. I changed that you mentioned. Please share some link to help me regarding name convention as you said in the session.

**Comment by hamidafghan** [comment]
Yeah. This [book](http://www.oracle.com/technetwork/java/codeconventions-150003.pdf) can help you about java standard convention powered by Oracle. @wahrez
